replicaCount: 2

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/eddiewebb/rollouts
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "12.3"

kargo:
  stage: dev

ingress:
  root_domain: rollouts.k8s.orb.local
