apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rollouts
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: nginx-gateway
  hostnames:
  - "{{ .Values.ingress.root_domain }}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /{{  .Release.Namespace }}
    backendRefs:
    - name: rollouts-svc-stable
      port: 80