apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rollouts
spec:
  parentRefs:
  - name: gateway
    namespace: nginx-gateway
  hostnames:
  - "{{  .Release.Namespace }}.{{ .Values.ingress.root_domain }}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: rollouts-svc-stable
      port: 80