apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.ingress.root_domain }}"
    http:
      paths:
      - pathType: Prefix
        path: /{{  .Release.Namespace }}
        backend:
          service:
            name: rollouts-svc-stable
            port:
              number: 80