project:
  group: akuityio:doesnotexist

image:
  repository: kennethreitz/httpbin
  selectionStrategy: Digest
  tag: latest
  containerPort: 80
  memoryLimit: 128Mi
  cpuLimit: 150m
ingress:
  custom_prefix: http-bin
rollouts:
  enabled: false

environments:
  staging: false
