name: Publish new image
run-name: Publish new image of rollouts binary

on:
  push:
    branches:
      - main
permissions:
  packages: write
  attestations: write
  contents: read
  id-token: write
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-rollouts-app

jobs:
  publish:
    defaults:
      run:
        working-directory: rollouts-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pick release color
        run: |
          COLORS=("red" "green" "blue" "yellow" "purple" "orange")
          INDEX=$(( $GITHUB_RUN_NUMBER % ${#COLORS[@]} ))
          echo "APP_COLOR=${COLORS[$INDEX]}" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        id: push
        with:
          context: rollouts-app
          push: true
          build-args: |
            COLOR=${{ env.APP_COLOR }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ github.run_number }}-${{ env.APP_COLOR }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  cleanup:
    name: ghcr.io cleanup action
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-tagged: 5
          delete-ghost-images: true
          delete-orphaned-images: true
          delete-untagged: true
          image: ${{ env.IMAGE_NAME}}
